
@startuml

skinparam backgroundColor #ffffff

frame "User" as pUser
frame "KeyFiltering()" as pTn
frame "Message-\nDispatching()" as pCore
frame "TextBox\n(InputFiltering())" as pTxt

database "- Frames" as sTnToUser
database "Bytes" as sUserToTn

database "- Frames" as sCoreToTn
database "- Keys\n  - Printable or\n  - Control" as sTnToCore

database "Clipboard" as sMsgClipboard

database "- Frame-\n  Fragments\n- current()\n- clipboard()" as sTxtToCore
database "- Keys\n\n- currentSet()\n- paste()" as sCoreToTxt

pUser -- sUserToTn
sUserToTn --> pTn
pUser <-- sTnToUser
sTnToUser -- pTn

pTn -- sTnToCore
sTnToCore --> pCore
pTn <-- sCoreToTn
sCoreToTn -- pCore

sMsgClipboard <-> pCore

pCore -- sCoreToTxt
sCoreToTxt --> pTxt
pCore <-- sTxtToCore
sTxtToCore -- pTxt

footer **TextBox** System Core and User Interface\n(C) DSP-Crowd Electronics GmbH

@enduml

